version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      postpipe-core:
        patterns:
          - "@postpipe-official/connector-core"
